version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/cache:/var/cache/nginx
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - openthreat-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://open-threats.com}
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-https://open-threats.com}
    restart: unless-stopped
    networks:
      - openthreat-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-openthreat}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-openthreat}
      - REDIS_URL=redis://redis:6379
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3000}
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - postgres
      - redis
      - ollama
    restart: unless-stopped
    networks:
      - openthreat-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
      replicas: 2

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-openthreat}
      - POSTGRES_USER=${POSTGRES_USER:-openthreat}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - openthreat-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
    command: >
      postgres
      -c shared_buffers=512MB
      -c effective_cache_size=1536MB
      -c maintenance_work_mem=128MB
      -c max_connections=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200

  redis:
    image: redis:7-alpine
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru --save 60 1000
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - openthreat-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A backend.celery_app worker --loglevel=info --concurrency=2
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-openthreat}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-openthreat}
      - REDIS_URL=redis://redis:6379
      - OLLAMA_HOST=http://ollama:11434
      - LLM_MODEL=llama3.2:1b
    depends_on:
      - postgres
      - redis
      - ollama
    restart: unless-stopped
    networks:
      - openthreat-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
      replicas: 2

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A backend.celery_app beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-openthreat}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-openthreat}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - openthreat-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - openthreat-network
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2G

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  ollama_data:
    driver: local

networks:
  openthreat-network:
    driver: bridge
