"""Initial schema

Revision ID: 5316abe9027f
Revises: 
Create Date: 2025-10-13 22:07:22.525806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5316abe9027f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=True),
    sa.Column('records_inserted', sa.Integer(), nullable=True),
    sa.Column('records_updated', sa.Integer(), nullable=True),
    sa.Column('records_failed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_id'), 'ingestion_runs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_source'), 'ingestion_runs', ['source'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_started_at'), 'ingestion_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.create_table('iocs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ioc_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=False),
    sa.Column('threat_type', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ioc_value_trgm', 'iocs', ['value'], unique=False, postgresql_using='gin', postgresql_ops={'value': 'gin_trgm_ops'})
    op.create_index(op.f('ix_iocs_first_seen'), 'iocs', ['first_seen'], unique=False)
    op.create_index(op.f('ix_iocs_id'), 'iocs', ['id'], unique=False)
    op.create_index(op.f('ix_iocs_ioc_type'), 'iocs', ['ioc_type'], unique=False)
    op.create_index(op.f('ix_iocs_value'), 'iocs', ['value'], unique=False)
    op.create_table('search_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_cache_cache_key'), 'search_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_search_cache_created_at'), 'search_cache', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_cache_expires_at'), 'search_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_search_cache_id'), 'search_cache', ['id'], unique=False)
    op.create_table('techniques',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tactics', sa.JSON(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('data_sources', sa.JSON(), nullable=True),
    sa.Column('detection', sa.Text(), nullable=True),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_techniques_id'), 'techniques', ['id'], unique=False)
    op.create_index(op.f('ix_techniques_technique_id'), 'techniques', ['technique_id'], unique=True)
    op.create_table('vulnerabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cve_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('cvss_vector', sa.String(length=200), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('modified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exploited_in_the_wild', sa.Boolean(), nullable=False),
    sa.Column('cisa_due_date', sa.Date(), nullable=True),
    sa.Column('cwe_ids', sa.JSON(), nullable=True),
    sa.Column('affected_products', sa.JSON(), nullable=True),
    sa.Column('vendors', sa.JSON(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('source_tags', sa.JSON(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vuln_cve_id_trgm', 'vulnerabilities', ['cve_id'], unique=False, postgresql_using='gin', postgresql_ops={'cve_id': 'gin_trgm_ops'})
    op.create_index('ix_vuln_description_trgm', 'vulnerabilities', ['description'], unique=False, postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.create_index('ix_vuln_title_trgm', 'vulnerabilities', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=True)
    op.create_index(op.f('ix_vulnerabilities_cvss_score'), 'vulnerabilities', ['cvss_score'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_exploited_in_the_wild'), 'vulnerabilities', ['exploited_in_the_wild'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_id'), 'vulnerabilities', ['id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_modified_at'), 'vulnerabilities', ['modified_at'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_priority_score'), 'vulnerabilities', ['priority_score'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_published_at'), 'vulnerabilities', ['published_at'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_severity'), 'vulnerabilities', ['severity'], unique=False)
    op.create_table('vulnerability_technique',
    sa.Column('vulnerability_id', sa.Integer(), nullable=False),
    sa.Column('technique_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('vulnerability_id', 'technique_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerability_technique')
    op.drop_index(op.f('ix_vulnerabilities_severity'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_published_at'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_priority_score'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_modified_at'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_exploited_in_the_wild'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cvss_score'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_index('ix_vuln_title_trgm', table_name='vulnerabilities', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_vuln_description_trgm', table_name='vulnerabilities', postgresql_using='gin', postgresql_ops={'description': 'gin_trgm_ops'})
    op.drop_index('ix_vuln_cve_id_trgm', table_name='vulnerabilities', postgresql_using='gin', postgresql_ops={'cve_id': 'gin_trgm_ops'})
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_techniques_technique_id'), table_name='techniques')
    op.drop_index(op.f('ix_techniques_id'), table_name='techniques')
    op.drop_table('techniques')
    op.drop_index(op.f('ix_search_cache_id'), table_name='search_cache')
    op.drop_index(op.f('ix_search_cache_expires_at'), table_name='search_cache')
    op.drop_index(op.f('ix_search_cache_created_at'), table_name='search_cache')
    op.drop_index(op.f('ix_search_cache_cache_key'), table_name='search_cache')
    op.drop_table('search_cache')
    op.drop_index(op.f('ix_iocs_value'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_ioc_type'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_id'), table_name='iocs')
    op.drop_index(op.f('ix_iocs_first_seen'), table_name='iocs')
    op.drop_index('ix_ioc_value_trgm', table_name='iocs', postgresql_using='gin', postgresql_ops={'value': 'gin_trgm_ops'})
    op.drop_table('iocs')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_started_at'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_source'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
